version: '3'
services:
  mongodb:
    image: mongo:6.0
    container_name: bid-my-hobby-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: mydatabase
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
