# Server configuration
server:
  port: 8080

# Spring configuration
spring:
  application:
    name: bid-my-hobby
  main:
    allow-bean-definition-overriding: true
  docker:
    compose:
      enabled: false
  
# Actuator configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true

# AWS Configuration
aws:
  s3:
    access-key: ${AWS_ACCESS_KEY:your-access-key}
    secret-key: ${AWS_SECRET_KEY:your-secret-key}
    region: ${AWS_REGION:us-east-1}
    bucket:
      name: ${AWS_BUCKET_NAME:hobby-images-bucket}
      metadata-prefix: metadata/
      images-prefix: images/
      users-prefix: users/
  ses:
    region: ${AWS_SES_REGION:${AWS_REGION:us-east-1}}
    from-email: ${AWS_SES_FROM_EMAIL:noreply@bidmyhobby.com}

# OpenAI Configuration
openai:
  api:
    key: ${OPENAI_API_KEY:openai_hobby_api_key}

# Admin key
admin:
  secret:
    key: ${ADMIN_SECRET_KEY:your-admin-secret-key}