/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.bidmyhobby.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class BidEvent extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -6387412363669553580L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"BidEvent\",\"namespace\":\"com.bidmyhobby.avro\",\"fields\":[{\"name\":\"bidId\",\"type\":\"string\"},{\"name\":\"userId\",\"type\":\"string\"},{\"name\":\"itemId\",\"type\":\"string\"},{\"name\":\"amount\",\"type\":\"double\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<BidEvent> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<BidEvent> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<BidEvent> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<BidEvent> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<BidEvent> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this BidEvent to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a BidEvent from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a BidEvent instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static BidEvent fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence bidId;
  private java.lang.CharSequence userId;
  private java.lang.CharSequence itemId;
  private double amount;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public BidEvent() {}

  /**
   * All-args constructor.
   * @param bidId The new value for bidId
   * @param userId The new value for userId
   * @param itemId The new value for itemId
   * @param amount The new value for amount
   */
  public BidEvent(java.lang.CharSequence bidId, java.lang.CharSequence userId, java.lang.CharSequence itemId, java.lang.Double amount) {
    this.bidId = bidId;
    this.userId = userId;
    this.itemId = itemId;
    this.amount = amount;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return bidId;
    case 1: return userId;
    case 2: return itemId;
    case 3: return amount;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: bidId = (java.lang.CharSequence)value$; break;
    case 1: userId = (java.lang.CharSequence)value$; break;
    case 2: itemId = (java.lang.CharSequence)value$; break;
    case 3: amount = (java.lang.Double)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'bidId' field.
   * @return The value of the 'bidId' field.
   */
  public java.lang.CharSequence getBidId() {
    return bidId;
  }


  /**
   * Sets the value of the 'bidId' field.
   * @param value the value to set.
   */
  public void setBidId(java.lang.CharSequence value) {
    this.bidId = value;
  }

  /**
   * Gets the value of the 'userId' field.
   * @return The value of the 'userId' field.
   */
  public java.lang.CharSequence getUserId() {
    return userId;
  }


  /**
   * Sets the value of the 'userId' field.
   * @param value the value to set.
   */
  public void setUserId(java.lang.CharSequence value) {
    this.userId = value;
  }

  /**
   * Gets the value of the 'itemId' field.
   * @return The value of the 'itemId' field.
   */
  public java.lang.CharSequence getItemId() {
    return itemId;
  }


  /**
   * Sets the value of the 'itemId' field.
   * @param value the value to set.
   */
  public void setItemId(java.lang.CharSequence value) {
    this.itemId = value;
  }

  /**
   * Gets the value of the 'amount' field.
   * @return The value of the 'amount' field.
   */
  public double getAmount() {
    return amount;
  }


  /**
   * Sets the value of the 'amount' field.
   * @param value the value to set.
   */
  public void setAmount(double value) {
    this.amount = value;
  }

  /**
   * Creates a new BidEvent RecordBuilder.
   * @return A new BidEvent RecordBuilder
   */
  public static com.bidmyhobby.avro.BidEvent.Builder newBuilder() {
    return new com.bidmyhobby.avro.BidEvent.Builder();
  }

  /**
   * Creates a new BidEvent RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new BidEvent RecordBuilder
   */
  public static com.bidmyhobby.avro.BidEvent.Builder newBuilder(com.bidmyhobby.avro.BidEvent.Builder other) {
    if (other == null) {
      return new com.bidmyhobby.avro.BidEvent.Builder();
    } else {
      return new com.bidmyhobby.avro.BidEvent.Builder(other);
    }
  }

  /**
   * Creates a new BidEvent RecordBuilder by copying an existing BidEvent instance.
   * @param other The existing instance to copy.
   * @return A new BidEvent RecordBuilder
   */
  public static com.bidmyhobby.avro.BidEvent.Builder newBuilder(com.bidmyhobby.avro.BidEvent other) {
    if (other == null) {
      return new com.bidmyhobby.avro.BidEvent.Builder();
    } else {
      return new com.bidmyhobby.avro.BidEvent.Builder(other);
    }
  }

  /**
   * RecordBuilder for BidEvent instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<BidEvent>
    implements org.apache.avro.data.RecordBuilder<BidEvent> {

    private java.lang.CharSequence bidId;
    private java.lang.CharSequence userId;
    private java.lang.CharSequence itemId;
    private double amount;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.bidmyhobby.avro.BidEvent.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.bidId)) {
        this.bidId = data().deepCopy(fields()[0].schema(), other.bidId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.userId)) {
        this.userId = data().deepCopy(fields()[1].schema(), other.userId);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.itemId)) {
        this.itemId = data().deepCopy(fields()[2].schema(), other.itemId);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.amount)) {
        this.amount = data().deepCopy(fields()[3].schema(), other.amount);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
    }

    /**
     * Creates a Builder by copying an existing BidEvent instance
     * @param other The existing instance to copy.
     */
    private Builder(com.bidmyhobby.avro.BidEvent other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.bidId)) {
        this.bidId = data().deepCopy(fields()[0].schema(), other.bidId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.userId)) {
        this.userId = data().deepCopy(fields()[1].schema(), other.userId);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.itemId)) {
        this.itemId = data().deepCopy(fields()[2].schema(), other.itemId);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.amount)) {
        this.amount = data().deepCopy(fields()[3].schema(), other.amount);
        fieldSetFlags()[3] = true;
      }
    }

    /**
      * Gets the value of the 'bidId' field.
      * @return The value.
      */
    public java.lang.CharSequence getBidId() {
      return bidId;
    }


    /**
      * Sets the value of the 'bidId' field.
      * @param value The value of 'bidId'.
      * @return This builder.
      */
    public com.bidmyhobby.avro.BidEvent.Builder setBidId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.bidId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'bidId' field has been set.
      * @return True if the 'bidId' field has been set, false otherwise.
      */
    public boolean hasBidId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'bidId' field.
      * @return This builder.
      */
    public com.bidmyhobby.avro.BidEvent.Builder clearBidId() {
      bidId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'userId' field.
      * @return The value.
      */
    public java.lang.CharSequence getUserId() {
      return userId;
    }


    /**
      * Sets the value of the 'userId' field.
      * @param value The value of 'userId'.
      * @return This builder.
      */
    public com.bidmyhobby.avro.BidEvent.Builder setUserId(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.userId = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'userId' field has been set.
      * @return True if the 'userId' field has been set, false otherwise.
      */
    public boolean hasUserId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'userId' field.
      * @return This builder.
      */
    public com.bidmyhobby.avro.BidEvent.Builder clearUserId() {
      userId = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'itemId' field.
      * @return The value.
      */
    public java.lang.CharSequence getItemId() {
      return itemId;
    }


    /**
      * Sets the value of the 'itemId' field.
      * @param value The value of 'itemId'.
      * @return This builder.
      */
    public com.bidmyhobby.avro.BidEvent.Builder setItemId(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.itemId = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'itemId' field has been set.
      * @return True if the 'itemId' field has been set, false otherwise.
      */
    public boolean hasItemId() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'itemId' field.
      * @return This builder.
      */
    public com.bidmyhobby.avro.BidEvent.Builder clearItemId() {
      itemId = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'amount' field.
      * @return The value.
      */
    public double getAmount() {
      return amount;
    }


    /**
      * Sets the value of the 'amount' field.
      * @param value The value of 'amount'.
      * @return This builder.
      */
    public com.bidmyhobby.avro.BidEvent.Builder setAmount(double value) {
      validate(fields()[3], value);
      this.amount = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'amount' field has been set.
      * @return True if the 'amount' field has been set, false otherwise.
      */
    public boolean hasAmount() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'amount' field.
      * @return This builder.
      */
    public com.bidmyhobby.avro.BidEvent.Builder clearAmount() {
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public BidEvent build() {
      try {
        BidEvent record = new BidEvent();
        record.bidId = fieldSetFlags()[0] ? this.bidId : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.userId = fieldSetFlags()[1] ? this.userId : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.itemId = fieldSetFlags()[2] ? this.itemId : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.amount = fieldSetFlags()[3] ? this.amount : (java.lang.Double) defaultValue(fields()[3]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<BidEvent>
    WRITER$ = (org.apache.avro.io.DatumWriter<BidEvent>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<BidEvent>
    READER$ = (org.apache.avro.io.DatumReader<BidEvent>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.bidId);

    out.writeString(this.userId);

    out.writeString(this.itemId);

    out.writeDouble(this.amount);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.bidId = in.readString(this.bidId instanceof Utf8 ? (Utf8)this.bidId : null);

      this.userId = in.readString(this.userId instanceof Utf8 ? (Utf8)this.userId : null);

      this.itemId = in.readString(this.itemId instanceof Utf8 ? (Utf8)this.itemId : null);

      this.amount = in.readDouble();

    } else {
      for (int i = 0; i < 4; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.bidId = in.readString(this.bidId instanceof Utf8 ? (Utf8)this.bidId : null);
          break;

        case 1:
          this.userId = in.readString(this.userId instanceof Utf8 ? (Utf8)this.userId : null);
          break;

        case 2:
          this.itemId = in.readString(this.itemId instanceof Utf8 ? (Utf8)this.itemId : null);
          break;

        case 3:
          this.amount = in.readDouble();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










