apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  # These are base64 encoded placeholders - replace with actual encoded values
  openai-api-key: c2stcHJvai1FXzZ1YzFyRnhNOFl5cFl3R2MwSGRzc1Bhbm9tMWpzcHhReUlta2xWMDBaVWZra1NKRi1NVndBUmYxQjVLSkpmTzhFNnlaeXpfUlQzQmxia0ZKbEk5Wk4talRhckNodkpnRWNQZkQ2SlYwejNTUjV6WFlhejU5Qm5uYVR1QnZNdEtWVkd4dGptajNnd2F0UGFlMzFkem82OGxBNEE=
  admin-secret-key: QnJhdm9QdWxzZTE5Iw==