apiVersion: v1
kind: Service
metadata:
  name: bid-my-hobby
  labels:
    app: bid-my-hobby
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: bid-my-hobby